name: Build Theos Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  THEOS: ${{ github.workspace }}/theos

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Cache Theos
      uses: actions/cache@v3
      with:
        path: ${{ env.THEOS }}
        key: ${{ runner.os }}-theos-${{ hashFiles('**/Makefile') }}
        restore-keys: |
          ${{ runner.os }}-theos-

    - name: Set up Theos environment
      if: steps.cache-theos.outputs.cache-hit != 'true'
      run: |
        brew update
        brew install ldid
        git clone --recursive https://github.com/theos/theos.git $THEOS
        git clone https://github.com/theos/sdks $THEOS/sdks

    - name: Set up environment variables
      run: |
        echo "PATH=$THEOS/bin:$PATH" >> $GITHUB_ENV
        echo "THEOS_DEVICE_IP=192.168.3.11" >> $GITHUB_ENV

    - name: Build Theos project
      run: |
        make clean
        make package FINALPACKAGE=1 THEOS_PACKAGE_SCHEME=rootless

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: built-package
        path: packages/*.deb

    - name: Display build logs on failure
      if: failure()
      run: |
        echo "Build failed. Displaying last 100 lines of make.log:"
        tail -n 100 make.log